services:
  postgres-db:
    image: postgres:16.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: ozer

  redis-db:
    image: redis:7.2-alpine
    ports:
      - '16379:6379'
